### ISSUE TITLE
style embeding

### ISSUE THREAD

**Issue by stefanovualto** [crisward/svelte-tag#1]
Hi Cris,

Well done with this wrapper, that is almost what I was looking for but then when I saw the href on the styling I thought that would create issue especially if I try to deploy and share my component outside.

Do you hitnk/know if it is possible to embed styles directly in the svelte app to avoid having to pass the URL of the bundled css?

Thank you in advance, good job on that one! frameworks and web components are hard to get along... 😄

**Comment by crisward** [comment]
To get the css into the webcomponent you'd need to get the generated css from the bundler (rollup / webpack) them pass the output into a script tag within the web component. Svelte adds hashes to all the classes to prevent style conflicts, so it's not just a case of grabbing the css.

That's a bit outside the scope of this wrapper, as it isn't a build tool as such.

If your component is fairly simple, inline styles would work, but I realise that's far from ideal. You can also use the compiler flag in svelte to generate web components, which may be closer to what you need.

**Comment by stefanovualto** [comment]
Thanks for your answer, I tried with split compilation (compile the entry with customComponent and the rest as a svelte app) but it is hacky, and I don't like that for production projects... based on this template https://github.com/redradix/svelte-custom-element-template.

Anyway, I guess I will have to dig deeper and understand better how to hack it in a cleaner way...

Thank you again for trying to make the webcomponent integration better with svelte... I guess we are not that far from being able to do it properly...

**Comment by crisward** [comment]
Feel free to fork this project. All of the code is in https://github.com/crisward/svelte-tag/blob/master/index.js

If you change the way the style tag is added at line 42 and instead insert an inline style tag with some very identifiable content, you may be able to do a bit of find and replace with rollup to insert your compiled css at that point.

eg 

```javascript
  let style = document.createElement('style');
  style.innerHTML=`--MYSTYLES--`
  root.appendChild(style); 
```

Then in rollup get the css from the svelte plugin, and inject it into the javascript with a replace on `--MYSTYLES--`

You'll only be able to do this with one component, but it should work. You'll need to take a look at the rollup and https://github.com/sveltejs/rollup-plugin-svelte docs.

Hope that helps.

**Comment by stefanovualto** [comment]
That's what I am look at right now, thank you!

But then I will have to also bind attribute and functions externally...

I started svelte one week ago and I am not used to rollup yet, it is nice learn new things... hopefully they will switch soon to snowpack 🚀  😄
