### ISSUE TITLE
THANKS!! and it works without referencing stylesheets

### ISSUE THREAD

**Issue by chmich** [crisward/svelte-tag#10]
Thanks a lot, chrisward, for creating that!

I used it without referencing a stylesheets 

```
import component from "svelte-tag"

import App from "../components/auto-select.svelte";
new component({component:App, tagname:"svelte-auto-select"})
```

and its applying all global styles and handling props giving to the CE.

**Comment by crisward** [comment]
If you don't have `shadow:true` set, any global css will be visible inside the component. The href attribute is only really needed if you want to inject css into the shadow dom.

Hope that make sense.

**Comment by chmich** [comment]
Thank you for clearify, crisward!
For me its perfect like it is.
BR,
Christian

**Comment by crisward** [comment]
No problem.
