### ISSUE TITLE
Issues With Slots

### ISSUE THREAD

**Issue by nickpoulos** [crisward/svelte-tag#3]
Does this technique work with slotted content as well?  

I am having an issue getting my slots to show up with a basic example and was not able to find a workaround.  Everything else seems to work properly --  props, events, etc.  

It seems like a strange quirk so it makes me feel like I am doing something incorrectly?

Any insights appreciated. 

Thanks for releasing this little package!

**Comment by crisward** [comment]
Slots should work fine.
There is a test here checking that.
https://github.com/crisward/svelte-tag/blob/master/tests/tag.test.js#L34

Perhaps share an example?

**Comment by nickpoulos** [comment]
Ahh my mistake, I came to the wrong codebase! 

I am actually using this snippet: https://github.com/sveltejs/svelte/issues/1748#issuecomment-583880664

I saw your comment underneath and kept the tab open to your project here. 

But now that slots do not appear to be working with the above snippet, I may just try out svelte-tag. 

Thanks!
